### ISSUE TITLE
[Bug] CUDA error when running sample code

### ISSUE THREAD

**Issue by youryz** [DLR-RM/stable-baselines3#345]
I am running the basic code to train a PPO agent on CartPole and it gives me an CUDA error:

RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

in "/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)

Python version 3.6.9

Pytorch version 1.8.0

Code is this:
```python
import gym

from stable_baselines3 import PPO

env = gym.make('CartPole-v1')

model = PPO('MlpPolicy', env, verbose=1)
model.learn(total_timesteps=10000)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, done, info = env.step(action)
    env.render()
    if done:
      obs = env.reset()

env.close()
```

**Comment by araffin** [comment]
Hello,
sounds definitely like a Pytorch/CUDA related issue, not a SB3 one...

Did you try just importing pytorch and using the GPU:
```python
import torch
torch.ones(10).cuda()
```

**Comment by youryz** [comment]
Thanks for the reply. Yeah i tried this code and it works well. Actually I can run my own deep learning projects (training + inference) without any problems. But I don't know why running this code gives me the issue.


> Hello,
> sounds definitely like a Pytorch/CUDA related issue, not a SB3 one...
> 
> Did you try just importing pytorch and using the GPU:
> 
> ```python
> import torch
> torch.ones(10).cuda()
> ```

**Comment by Miffyli** [comment]
If by "sample code" you mean the code araffin provided, then yes, it is a torch installation / cuda installation issue. You might want to check that you are launching code with the right Python installation/environment etc.

If no further bugs raise up related to stable-baselines3 you may close this issue (we do not offer custom tech support here).

**Comment by youryz** [comment]
Actually no @Miffyli , the code araffin provides works. My own deep learning projects based on Pytorch also works (MLP training & inference). What I mean sample code is the code in my initial post, which is used to train a PPO agent, and I post it again here:

`import gym

from stable_baselines3 import PPO

env = gym.make('CartPole-v1')

model = PPO('MlpPolicy', env, verbose=1)
model.learn(total_timesteps=10000)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, done, info = env.step(action)
    env.render()
    if done:
      obs = env.reset()

env.close()`

**Comment by araffin** [comment]
> Actually no @Miffyli , the code araffin provides works. My own deep learning projects based on Pytorch also works (MLP training & inference). What I mean sample code is the code in my initial post, which is used to train a PPO agent, and I post it again here:
> 
> ```
> import gym
> 
> from stable_baselines3 import PPO
> 
> env = gym.make('CartPole-v1')
> 
> model = PPO('MlpPolicy', env, verbose=1)
> model.learn(total_timesteps=10000)
> 
> obs = env.reset()
> for i in range(1000):
>     action, _states = model.predict(obs, deterministic=True)
>     obs, reward, done, info = env.step(action)
>     env.render()
>     if done:
>       obs = env.reset()
> 
> env.close()
> ```
> 
> I've checked my Pytorch/CUDA and there's no problem with them. I will check again in case. But I don't think there should be any problem with them since my past projects worked well.

the error that you have is definitely a pytorch/cuda error. I have tested SB3 with python 3.6 and pytorch 1.8 on my machine and on a google colab instance and did not get any error...
i guess the code will also run if you use the cpu only.

**Comment by youryz** [comment]
> > Actually no @Miffyli , the code araffin provides works. My own deep learning projects based on Pytorch also works (MLP training & inference). What I mean sample code is the code in my initial post, which is used to train a PPO agent, and I post it again here:
> > ```
> > import gym
> > 
> > from stable_baselines3 import PPO
> > 
> > env = gym.make('CartPole-v1')
> > 
> > model = PPO('MlpPolicy', env, verbose=1)
> > model.learn(total_timesteps=10000)
> > 
> > obs = env.reset()
> > for i in range(1000):
> >     action, _states = model.predict(obs, deterministic=True)
> >     obs, reward, done, info = env.step(action)
> >     env.render()
> >     if done:
> >       obs = env.reset()
> > 
> > env.close()
> > ```
> > 
> > 
> > I've checked my Pytorch/CUDA and there's no problem with them. I will check again in case. But I don't think there should be any problem with them since my past projects worked well.
> 
> the error that you have is definitely a pytorch/cuda error. I have tested SB3 with python 3.6 and pytorch 1.8 on my machine and on a google colab instance and did not get any error...
> i guess the code will also run if you use the cpu only.

I switched to cpu by passing 'cpu' to PPO, it trains two epochs, then it breaks again and gives me the same CUDA error. 

I have two different machines and the code works on neither one. 

Anyway I will check my CUDA installation.

Thanks

**Comment by araffin** [comment]
closing as not related to SB3.

**Comment by youryz** [comment]
> Same issue for me, seems to be torch 1.8 related ([pytorch/pytorch#53336](https://github.com/pytorch/pytorch/issues/53336))
> 
> Downgrading to torch 1.7.1 seems to work fine for now.

@ac-93 You are TRULY a life savior!
